# Generated by Django 6.1 on 2026-08-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='programming', max_length=100),
        ),
    ]
