# Generated by Django 6.1 on 2026-08-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_courserating'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserating',
            name='review',
            field=models.TextField(blank=True),
        ),
    ]
